# Generated by Django 4.1 on 2024-04-24 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('Color', 'Color'), ('size', 'Size')], max_length=100),
        ),
    ]
